### ISSUE TITLE
Runtimer index error when running to crack mongo-cr hashes

### ISSUE THREAD

**Issue by 0x5929** [averagesecurityguy/krkr#1]
# ./krkr -f /root/Documents/mongodb/administrator.hash  -t mongo-cr -w /usr/share/wordlists/rockyou.txt
Loaded 1 hashes.
Loaded 14336793 words.
panic: runtime error: index out of range [1] with length 1

goroutine 37 [running]:
main.(*MongoCR).Hash(0x5d4518, 0xc0000b6000, 0x40, 0xc008672000, 0x6)
        /opt/krkr/mongocr.go:29 +0x36f
main.main.func2(0xc0000140e0, 0xc0000500c0, 0xc0000822c0)
        /opt/krkr/main.go:93 +0x9b
created by main.main
        /opt/krkr/main.go:90 +0x5dc
#

**Comment by 0x5929** [comment]
Same as well when trying mongo-scram as well.

**Comment by hffaust** [comment]
same error here... I think possible because it has to be in the format of `username:hash` ... when I reformatted my hash it seemed to fix it. Still not finding the hash in my case, could be a wordlist problem though.
